import path from 'path';
import fs from 'fs-extra';
import ora from 'ora';
import chalk from 'chalk';

export async function scaffoldRoot(projectDir, config) {
  const spinner = ora({ text: chalk.cyan('Writing root files…'), color: 'cyan' }).start();

  try {
    const { projectName, useTypeScript, dryRun } = config;

    if (dryRun) {
      spinner.info(chalk.dim('[dry-run] Root files would be written'));
      return;
    }

    const rootPkg = {
      name: projectName,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'concurrently "npm run dev --prefix server" "npm run dev --prefix client"',
        'dev:server': 'npm run dev --prefix server',
        'dev:client': 'npm run dev --prefix client',
        build: 'npm run build --prefix client',
        install: 'npm install --prefix server && npm install --prefix client',
      },
      devDependencies: {
        concurrently: '^8.2.2',
      },
    };

    await fs.writeJSON(path.join(projectDir, 'package.json'), rootPkg, { spaces: 2 });

    const gitignore = `# Dependencies
node_modules/
.pnp
.pnp.js

# Build output
dist/
build/
.next/
out/

# Environment variables (never commit!)
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# OS & editor
.DS_Store
Thumbs.db
.idea/
.vscode/
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# TypeScript
*.tsbuildinfo

# Coverage reports
coverage/
.nyc_output/
`;

    await fs.outputFile(path.join(projectDir, '.gitignore'), gitignore);

    const ts = useTypeScript ? ' (TypeScript)' : '';
    const readme = `# ${projectName}${ts}

> Generated by [create-mern-pro](https://github.com/your-username/create-mern-pro) 🚀

## Stack

- **Frontend**: React + Vite + Tailwind CSS
- **Backend**: Node.js + Express.js
- **Database**: MongoDB + Mongoose
- **Language**: ${useTypeScript ? 'TypeScript' : 'JavaScript'}

## Getting Started

### Prerequisites
- Node.js >= 18
- MongoDB (local or Atlas)

### Installation

\`\`\`bash
# Install all dependencies
npm run install

# Start development servers (frontend + backend concurrently)
npm run dev
\`\`\`

### Individual servers

\`\`\`bash
# Backend only (http://localhost:5000)
npm run dev:server

# Frontend only (http://localhost:5173)
npm run dev:client
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── client/           # React + Vite frontend
│   ├── src/
│   │   ├── components/
│   │   ├── pages/
│   │   ├── hooks/
│   │   ├── utils/
│   │   └── store/    # State management (if selected)
│   └── ...
└── server/           # Express backend
    ├── config/       # DB connection & env config
    ├── controllers/  # Route handlers / business logic
    ├── middleware/   # Auth, error handling, etc.
    ├── models/       # Mongoose schemas
    ├── routes/       # API route definitions
    └── ...
\`\`\`

## Environment Variables

Copy \`.env.example\` to \`.env\` in the \`server/\` directory and fill in your values.

## API Health Check

\`\`\`
GET http://localhost:5000/api/health
\`\`\`

## License

MIT
`;

    await fs.outputFile(path.join(projectDir, 'README.md'), readme);

    spinner.succeed(chalk.green('Root files created'));
  } catch (err) {
    spinner.fail(chalk.red('Failed to write root files'));
    throw err;
  }
}
